// NOTE - This file is auto-generated by hgen. DO NOT MODIFY!

// openddl.h

enum class StructureType : u32;
struct DerivedTypeMapping;
enum class PrimitiveDataType : u8;
enum class PrimitiveStructureType : u8;
struct Subarray;
struct SubarrayWithStates;
struct PrimitiveStructure;
enum class PropertyName : u32;
struct DerivedPropertyMapping;
struct DerivedMappings;
struct RefValue;
union RawPrimitiveValue;
struct PrimitiveValue;
struct Property;
struct DerivedStructure;
enum class StructureId : u32;
struct Structure;
struct StructureListReader;
struct PropertyListReader;
struct OpenDdlResult;

// parse.h

struct DataListUnknownLength;
struct DataArrayList;

// scan.h

enum class TokenType : u8;
struct Token;
struct Scanner;

// parse.cpp

struct Utf8ByteMetadata;

// scan.cpp

struct ReservedWord;
