// NOTE - This file is auto-generated by hgen. DO NOT MODIFY!

// simple_scan.h

internal void InitScanner(ZStringScanner * scanner, char * contents);
internal void InitScanner(StringScanner * scanner, String contents);

// simple_scan.cpp

namespace SimpleScan
{

inline bool IsWhitespace(char c);
inline char PeekChar(ZStringScanner * scanner);
inline char PeekChar(ZStringScanner * scanner, uint cBytesLookahead);
internal char NextChar(ZStringScanner * scanner);
inline bool MatchNextChar(ZStringScanner * scanner, char c);
inline bool IsAtEofChar(ZStringScanner * scanner);
inline String ConsumeUntil(ZStringScanner * scanner, char * candidates, int cntCandidate);
inline String ConsumeUntil(ZStringScanner * scanner, char c);
inline String ConsumePast(ZStringScanner * scanner, char * candidates, int cntCandidate);
inline String ConsumePast(ZStringScanner * scanner, char c);
inline String ConsumeWhitespace(ZStringScanner * scanner);
inline String ConsumeUntilWhitespace(ZStringScanner * scanner);
inline char PeekChar(StringScanner * scanner);
inline char PeekChar(StringScanner * scanner, uint cBytesLookahead);
internal char NextChar(StringScanner * scanner);
inline bool MatchNextChar(StringScanner * scanner, char c);
inline bool IsAtEofChar(StringScanner * scanner);
inline String ConsumeUntil(StringScanner * scanner, char * candidates, int cntCandidate);
inline String ConsumeUntil(StringScanner * scanner, char c);
inline String ConsumePast(StringScanner * scanner, char * candidates, int cntCandidate);
inline String ConsumePast(StringScanner * scanner, char c);
inline String ConsumeWhitespace(StringScanner * scanner);
inline String ConsumeUntilWhitespace(StringScanner * scanner);

} // namespace SimpleScan

