// NOTE - This file is auto-generated by hgen. DO NOT MODIFY!

// opengex.h

enum class OpenGexType : u32;
enum class OpenGexProperty : u32;
struct Metric;
struct Transform;
struct VertexArray;
struct IndexArray;
struct Mesh;
enum class GeometryFlags : u8;
struct GeometryObject;
enum class MaterialAttrib : u8;
struct Param;
struct Color;
struct Material;
struct GeometryNode;
struct OpenGexResult;
struct UnresolvedReference;
struct ReferenceTracker;

// opengex.cpp

struct MaterialRefFixup;
