// NOTE - This file is auto-generated by hgen. DO NOT MODIFY!

// opengex.h

inline Metric DefaultMetric(Metric::Key key);

// opengex.cpp

internal bool ReadMetric(DerivedStructure * structure, Metric * poResult);
internal bool ReadName(DerivedStructure * structure, String * poResult, MemoryRegion memory);
internal bool ReadColor(DerivedStructure * structure, Color * poResult, OpenGexType containingType);
internal bool ReadParam(DerivedStructure * structure, Param * poResult, OpenGexType containingType);
internal bool ReadMaterial(DerivedStructure * structure, Material * poResult, MemoryRegion memory);
internal bool ReadTransform(DerivedStructure * structure, Transform * poResult);
internal bool ReadIndexArray(DerivedStructure * structure, IndexArray * poResult, Mesh::PrimitiveType containingMeshPrimitiveType);
internal bool ReadVertexArray(DerivedStructure * structure, VertexArray * poResult);
internal bool ReadMesh(DerivedStructure * structure, Mesh * poResult, MemoryRegion memory);
internal bool ReadGeometryProperties(DerivedStructure * structure, GeometryFlags * poResult);
internal bool ReadGeometryNode(DerivedStructure * structure, GeometryNode * poResult, ReferenceTracker * refTracker, MemoryRegion memory);
internal bool ReadGeometryObject(DerivedStructure * structure, GeometryObject * poResult, MemoryRegion memory);
internal OpenGexResult ImportOpenGexFileContents(char * fileContents, MemoryRegion memory);
